### ISSUE TITLE
Whole beamline propagation

### ISSUE THREAD

**Issue by aljosahafner** [oasys-elettra-kit/OASYS1-Wiser#36]
* test
* implement if not working

**Comment by aljosahafner** [comment]
Finish by 26. 3.

**Comment by aljosahafner** [comment]
I am raising an error if `input_data == None`. This is incompatible with `PropagationMode.WHOLE_BEAMLINE`. The questions are:
* Is this mode needed?
* What is the difference between ticking the box `Automatic execution` when setting the widget and using `PropagationMode.WHOLE_BEAMLINE`

Before these two are answered I am not working on this.

**Comment by capitanevs** [comment]
The first two lines are cryptical to me, if you do not provide me further context.

But coming to point 1 and 2, I would say that you are right: "automatic execution" and "whole beamline propagation" are very similar.

The intended difference was:
- automatic execution "pushes the data flow" => you click an a widget, then the execution goes on untill a "automatic execution = false" is found. The propagation occurs from the widget to the end.
- whole beamline propagation was supposed to "pull the data flow" => you click on a widget, and then the beam is propagate from the source to that widget.

Luca introduced it because of different WISER and OASYS architecture.

For sake of simplicity, I would say:
let's try to use "automatic execution". If it works smoothly, then we will remove it even from the menu.

**Comment by aljosahafner** [comment]
Yes, this is what I think as well.

The first two lines were meant as a comment to me :)

**Comment by capitanevs** [comment]
For the moment, the behavior desired of "Full beamline propagation" is covered by using the checkbock "automatic computing" in the widget GUI.

Let's close the issue.
